# A short, descriptive name of this building block collection
name: OGC API Records

# Short abstract for this collection (optional)
abstract: |
  Building Blocks for OGC API Records, components and extensions

# Description for this collection (optional)
description: |
  A set of Building Blocks to allow reuse, testing and documentation of elements and extensions of OGC API Records.
  
  These are re-used by the [GeoDCAT implementation](../geodcat-ogc-api-records), binding Records schemas to DCAT and GeoDCAT ontologies.

identifier-prefix: ogc.api.records.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
  - https://rob-metalinkage.github.io/bblocks-ogcapi-features/build/register.json

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
